<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>MicroFramework</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <link href="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.2.1/css/bootstrap.min.css" rel="stylesheet">

        <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>

    <body>

        <div class="container">

            <div class="navbar navbar-inverse" style="margin-top: 20px;">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="brand" href="/">MicroFramework</a>
                        <div class="pull-right">
                            <ul class="nav">
                                <li><a href="/">Home</a></li>
                                <li><a href="/news">News</a></li>
                                <li><a href="https://github.com/Nice2MeatU/vulnerable-app" target="_blank">GitHub</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>

            <?= $content ?>


            <hr>

            <div class="footer">
                <p>&copy; MicroFramework 2012</p>
            </div>

        </div>

    </body>
</html>